name: Anchore Scan
on: 
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker Build
      run: docker build . --file Dockerfile --tag testrepo/testimage9:latest
    - uses: anchore/scan-action@v2
      with:
        image-reference: "testrepo/testimage9:latest"
        dockerfile-path: "./Dockerfile"
        fail-build: false
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: AnchoreReports
        path: ./anchore-reports/
